### ISSUE TITLE
好多文件丢失

### ISSUE THREAD

**Issue by wintersweet123** [GeekZooStudio/ECMobile_iOS#6]
![2016-03-03 2 22 36](https://cloud.githubusercontent.com/assets/10936828/13486365/718bb93a-e14b-11e5-80b0-dff4a97965b5.png)

**Comment by wintersweet123** [comment]
会员注册页面显示不粗来 ios9.2

**Comment by jiftle** [comment]
我也遇到了

**Comment by jiftle** [comment]
编译版本的问题，使用xcode5.1可以编译通过

**Comment by purplepeng** [comment]
支付暂时去掉了，现在可以编译通过了。
