### ISSUE TITLE
最受不了的就是项目打开运行不了的了

### ISSUE THREAD

**Issue by YuDiyi** [GeekZooStudio/ECMobile_iOS#7]
非常感谢能够分享这套源码，但是打开运行不了是什么鬼，还有就是文件夹命名太诡异了，类名也是，根本找不到对应的类。既然是用来分享的，就应该达到程序员直接交流的目的，这什么都看不懂，看了不到三分钟就不想看了。

**Comment by purplepeng** [comment]
A0_SigninBoard_iPhone类似这种命名；XX_编号是和Android统一的，_iPhone指的是iPhone屏幕上，有后缀可能是_iPad。
